# Generated by Django 2.2 on 2019-05-22 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMIN71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_create', models.DateField(auto_now_add=True)),
                ('c_nikappr', models.CharField(max_length=6)),
                ('c_po', models.CharField(max_length=8)),
                ('d_received', models.DateField()),
                ('b_isclosedr', models.BooleanField(default=False)),
                ('c_invoice', models.CharField(max_length=20)),
                ('c_packinglist', models.CharField(max_length=20)),
                ('c_boxno', models.CharField(max_length=10)),
                ('e_certificate', models.CharField(max_length=8)),
                ('e_other', models.CharField(max_length=29)),
                ('c_awb', models.CharField(max_length=20)),
                ('d_awb', models.DateField()),
                ('c_hawb', models.CharField(max_length=12)),
                ('d_hawb', models.DateField()),
                ('c_bc23', models.CharField(max_length=20)),
                ('d_bc23', models.DateField()),
                ('c_negaraasal', models.CharField(choices=[('US', 'US'), ('UK', 'UK'), ('SG', 'SG'), ('ID', 'ID'), ('AU', 'AU'), ('CA', 'CA'), ('UA', 'UA'), ('GM', 'GM'), ('MY', 'MY'), ('JP', 'JP'), ('PH', 'PH'), ('DK', 'DK'), ('IR', 'IR'), ('ES', 'ES'), ('SE', 'SE'), ('HK', 'HK')], max_length=2)),
                ('c_aju', models.CharField(max_length=29)),
                ('d_aju', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TMIN72',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nikappr', models.CharField(max_length=6)),
                ('i_itemno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('i_qreceived', models.DecimalField(decimal_places=2, max_digits=6)),
                ('i_qship', models.DecimalField(decimal_places=2, max_digits=6)),
                ('n_um', models.CharField(max_length=2)),
                ('f_in71', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.TMIN71')),
            ],
        ),
        migrations.CreateModel(
            name='TMIN73',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_qacc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('c_cert', models.CharField(max_length=1)),
                ('c_e', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('c_cond', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('f_in72', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.TMIN72')),
            ],
        ),
        migrations.CreateModel(
            name='IVR7020H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=8)),
                ('po', models.CharField(max_length=25)),
                ('created', models.DateField()),
                ('byr', models.CharField(max_length=3)),
                ('s1', models.CharField(max_length=1)),
                ('pg', models.CharField(max_length=2)),
                ('f1', models.CharField(max_length=1)),
                ('p1', models.CharField(max_length=1)),
                ('c1', models.CharField(max_length=1)),
                ('pt', models.CharField(max_length=1)),
                ('pi', models.CharField(max_length=3)),
                ('pjk', models.CharField(max_length=3)),
                ('itm', models.PositiveIntegerField()),
                ('pr', models.CharField(max_length=8)),
                ('wom', models.CharField(max_length=6)),
                ('sandi', models.CharField(max_length=4)),
                ('partnumber', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('duedate', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=6)),
                ('um', models.CharField(max_length=2)),
                ('mtu', models.CharField(max_length=3)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extpricerph', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(max_length=6)),
                ('vendorname', models.CharField(max_length=25)),
                ('f2', models.CharField(max_length=2)),
                ('so', models.CharField(max_length=2)),
                ('sr', models.CharField(max_length=2)),
                ('hs', models.CharField(max_length=15)),
                ('received', models.DateField()),
                ('inspected', models.DateField()),
                ('stored', models.DateField()),
                ('posts3', models.DateField()),
                ('c2', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('dokument', models.CharField(max_length=1)),
                ('engdisp', models.CharField(max_length=1)),
                ('lifetime', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
            ],
            options={
                'unique_together': {('master', 'itm')},
            },
        ),
    ]
