# Generated by Django 2.2 on 2019-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr7020h',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='inspected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='posts3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='stored',
            field=models.DateField(blank=True, null=True),
        ),
    ]
