# Generated by Django 2.2 on 2019-05-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_auto_20190522_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr7020h',
            name='extpricerph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='unitprice',
            field=models.FloatField(),
        ),
    ]
