# Generated by Django 2.2 on 2019-05-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_auto_20190522_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr7020h',
            name='dokument',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ivr7020h',
            name='engdisp',
            field=models.CharField(max_length=20),
        ),
    ]
