# Generated by Django 2.2 on 2019-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_auto_20190522_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr7020h',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
