# Generated by Django 2.2 on 2019-05-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_auto_20190522_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmin71',
            name='c_aju',
            field=models.CharField(blank=True, max_length=29),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_awb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_bc23',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_hawb',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_aju',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_awb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_bc23',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_hawb',
            field=models.DateField(blank=True, null=True),
        ),
    ]
