# Generated by Django 2.2 on 2019-05-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_auto_20190523_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmin71',
            name='b_isclosedr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_boxno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_invoice',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_negaraasal',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('SG', 'SG'), ('ID', 'ID'), ('AU', 'AU'), ('CA', 'CA'), ('UA', 'UA'), ('GM', 'GM'), ('MY', 'MY'), ('JP', 'JP'), ('PH', 'PH'), ('DK', 'DK'), ('IR', 'IR'), ('ES', 'ES'), ('SE', 'SE'), ('HK', 'HK')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_nikappr',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_packinglist',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='c_po',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='d_received',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='e_certificate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tmin71',
            name='e_other',
            field=models.CharField(blank=True, max_length=29),
        ),
    ]
