# Generated by Django 2.2 on 2019-05-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_auto_20190523_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tmin71',
            unique_together={('c_po', 'd_received')},
        ),
    ]
