# Generated by Django 2.2 on 2019-05-27 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_auto_20190523_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmin71',
            options={'permissions': (('approve_tmin71', 'Can Approve TMIN71'), ('print_tmin71', 'Can Print TMIN71'))},
        ),
        migrations.AlterModelOptions(
            name='tmin72',
            options={'permissions': (('approve_tmin72', 'Can Approve TMIN71'),)},
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='c_nikappr',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='f_in71',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.TMIN71'),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='i_qreceived',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='i_qship',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='f_in72',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchasing.TMIN72'),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='i_qacc',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='tmin72',
            unique_together={('f_in71', 'i_itemno')},
        ),
        migrations.CreateModel(
            name='TMIN76',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_release', models.DateField()),
                ('c_drno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('c_sts', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('f_in73', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchasing.TMIN73')),
            ],
        ),
    ]
