# Generated by Django 2.2 on 2019-05-28 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_auto_20190527_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmin72',
            name='c_asterik',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='tmin72',
            name='c_partin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tmin72',
            name='c_partnumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='i_itemno',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='i_qreceived',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='i_qship',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tmin72',
            name='n_um',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
