# Generated by Django 2.2 on 2019-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_auto_20190612_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmin73',
            name='c_cond',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='c_e',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='i_qacc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
