# Generated by Django 2.2 on 2019-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_auto_20190612_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmin72',
            options={'permissions': (('approve_tmin72', 'Can Approve TMIN72'),)},
        ),
        migrations.AlterModelOptions(
            name='tmin73',
            options={'permissions': (('approve_tmin73', 'Can Approve TMIN73'),)},
        ),
        migrations.AddField(
            model_name='tmin76',
            name='c_npo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='tmin76',
            name='i_qreject',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
