# Generated by Django 2.2 on 2019-06-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_auto_20190612_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmin72',
            name='d_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmin73',
            name='d_create',
            field=models.DateField(blank=True, null=True),
        ),
    ]
