# Generated by Django 2.2 on 2019-06-18 02:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_auto_20190614_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMIN75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_create', models.DateField(blank=True, null=True)),
                ('c_ciridap', models.CharField(blank=True, max_length=10)),
                ('c_owner', models.CharField(blank=True, max_length=3)),
                ('c_bin', models.CharField(blank=True, max_length=10)),
                ('c_recvno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('f_in73', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchasing.TMIN73')),
            ],
        ),
    ]
