# Generated by Django 2.2 on 2019-06-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_tmin75'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmin71',
            name='c_nik',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='tmin72',
            name='c_nik',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='tmin73',
            name='c_nik',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='tmin75',
            name='c_nik',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='tmin76',
            name='c_nik',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='tmin75',
            name='c_bin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tmin75',
            name='c_owner',
            field=models.CharField(max_length=3),
        ),
    ]
