# Generated by Django 2.2 on 2019-07-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0017_auto_20190708_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmin71',
            options={'ordering': ['-c_po', '-d_create', '-d_received'], 'permissions': (('approve_tmin71', 'Can Approve TMIN71'), ('print_tmin71', 'Can Print TMIN71'))},
        ),
        migrations.AlterUniqueTogether(
            name='tmin72',
            unique_together=set(),
        ),
    ]
