# Generated by Django 2.2 on 2019-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_auto_20190710_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmin73',
            name='c_cert',
            field=models.CharField(choices=[('1', '1 - Manual / Brocure'), ('2', '2 - Cert of Warranty'), ('3', '3 - Engine Document'), ('4', '4 - Cert of Calibration'), ('5', '5 - Cert of Origin'), ('6', '6 - Cert of Test / T Rep'), ('7', '7 - Cert of Comformance'), ('8', '8 - Cert of Analys'), ('9', '9 - Cert of Airworthines'), ('A', 'A - Cert of Mech Char'), ('B', 'B - Form FAA 8130-4'), ('C', 'C - Form FAA 8130-3'), ('D', 'D - EASA Form 1'), ('E', 'E - Form FAA 8130-3 & DAAO 21-18'), ('F', 'F - EASA Form 1 & DAAO 21-18'), ('G', 'G - TCCA 24-0078'), ('H', 'H - Dual EASA Form 1 & FAA 8130-3'), ('I', 'I - DAAO 21-18'), ('J', 'J - Hydrostatic Test Result'), ('K', 'K - Burst Test Result'), ('L', 'L - ECER110 & OR ISO 11439'), ('M', 'M - Cert of Material'), ('N', 'N - IDS (Inspection Data Sheet)'), ('O', 'O - DUAL (FAA 8130-3 & EASA F1 or FAA 8130-3 Only'), ('P', 'P - DUAL (FAA 8130-3 & EASA F1 or EASA Form Only'), ('Q', 'Q - FAA 8130-3 or EASA Form 1'), ('R', 'R - Ok for Assy')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='c_cond',
            field=models.CharField(choices=[('0', '0 - Unserviceable'), ('1', '1 - New'), ('2', '2 - Farm Out'), ('3', '3 - Repair In House'), ('4', '4 - OHC'), ('5', '5 - Serviceable'), ('6', '6 - Repairable for Trading'), ('7', '7 - Repair / Modified'), ('8', '8 - Inspected / New'), ('9', '9 - Inspected / As Remove'), (' ', '  - Unserviceable')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tmin73',
            name='c_e',
            field=models.CharField(choices=[('1', '1 - DGCA'), ('2', '2 - FAA'), ('3', '3 - EASA'), ('4', '4 - FAA & EASA'), ('5', '5 - DGCA & FAA'), ('6', '6 - DGCA & EASA'), ('7', '7 - ALL AUTHORITY'), ('8', '8 - N/A')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='tmin72',
            unique_together={('f_in71', 'i_itemno')},
        ),
    ]
