# Generated by Django 2.2 on 2019-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_timestamp', models.DateTimeField(auto_now_add=True)),
                ('c_nik', models.CharField(max_length=255)),
                ('c_trx', models.CharField(max_length=255)),
                ('c_func', models.CharField(max_length=255)),
                ('c_key', models.CharField(max_length=255)),
            ],
        ),
    ]
